FORMAT: 1A
HOST: https://onearea.online:3000

# Area API

Documentation of Area-Project API

# Group Basic

## Check request [/]

### Welcome Message [GET]

This is the main route containing a welcome message to watch if the server is up.

+ Response 200 (text/html)

        Server Instance V2

# Group OAuth2

## First Step OAuth [/get_oauth_url?id={id}]

### Get OAuth Url [GET]

This is for get the OAuth Url to get the Authorization Code (first step).

+ Parameters

    + id (number) - ID of the Current User

+ Response 200 (application/json)

        "https://accounts.google.com/o/oauth2/v2/auth?client_id=171093942489-7pe0ilftvscuv5runqumdoab1la5c4la.apps.googleusercontent.com
        &redirect_uri=https%3A%2F%2Fonearea.online%3A3000%2Foauth
        &response_type=code
        &scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube
        &state={id}"

## Second Step OAuth [/oauth?state={id}&code={code}]

### Redirect Uri [GET]

This is a route for the redirect uri settings.

+ Parameters

    + id (number) - ID of the Current User
    + code (string) - The authorization Code for get the access Token
    
+ Response 200 (text/html)

        OK
        
# Group Authentification

## Login Request [/login]

### Connect user [POST]

This route is for login a user already registered in database.

+ username (string) - The username of the user who want to connect
+ password (string) - The password of the user who want to connect

+ Request (application/json)

        {
            "username": "user",
            "password": "password"
        }
        
+ Response 200 (application/json)

+ Response 401 (text/html)

        Username user not found

+ Response 503 (text/html)

        Error With the Database

## Register Request [/register]

### Register user [POST]

This route is for login a user already registered in database.

+ username (string) - The username of the user who want to register
+ password (string) - The password of the user who want to register

+ Request (application/json)

        {
            "username": "user",
            "password": "password"
        }
        
+ Response 200 (application/json)

+ Response 503 (text/html)

        Error With the Database

# Group Services

## Service Set [/service/active/set]

### Set a service for user [POST]

This route is for set a service with his name for a user.

+ service_name (string) - The service name
+ active_state (booléen) - The state of the service ( if is active or not )
+ id (number) - The ID of the user to set the service name

+ Request (application/json)

        {
            "service_name": "intra",
            "active_state": true,
            "id": 5
        }

+ Response 200 (application/json)

+ Response 503 (text/html)

        Error With the Database

## Service Get [/service/active/get]

### Get a service of user [POST]

This route is for get a service with his name of a user.

+ service_name (string) - The service name
+ id (number) - The ID of the user to get the service name

+ Request (application/json)

        {
            "service_name": "google",
            "id": 2
        }

+ Response 200 (application/json)

        {
            "token": "token.google.com",
            "is_active": true
        }

+ Response 503 (text/html)

        Error With the Database

## Service Get All [/service/active/getall]

### Get all service [POST]

This route is for get all service who is linked to a user.

+ id (number) - The ID of the user to get all service

+ Request (application/json)

        {
            "service_name": "google",
            "id": 2
        }

+ Response 200 (application/json)

        {
            "token": "token.google.com",
            "is_active": true
        }

+ Response 503 (text/html)

        Error With the Database

## Service Set Token [/service/token/set]

### Set the token of a service [POST]

This route is for set the token value of a service name.

+ service_name (string) - The service name
+ token (string) - The token to set
+ id (number) - The ID of the user to set the token of the service name

+ Request (application/json)

        {
            "service_name": "intra",
            "token": "token.intra.eu",
            "id": 3
        }

+ Response 200 (text/html)

        OK

+ Response 503 (text/html)

        Error With the Database

# Group Actions

## Action Get All [/action/getall]

### Get all action [POST]

This route is for get all action who is linked to a user.

+ id (number) - The ID of the user to get all action

+ Request (application/json)

        {
            "id": 2
        }

+ Response 200 (application/json)

        {
            "area": {
                "is_active": true
            },
            "news": {
                "is_active": false
            },
            "covid": {
                "is_active": false
            },
            "intra": {
                "token": "token.intra.eu",
                "is_active": true
            },
            "crypto": {
                "is_active": false
            },
            "google": {
                "token": "token.google.com",
                "is_active": true
            },
            "weather": {
                "is_active": false
            }
        }

+ Response 503 (text/html)

        Error With the Database

## Action of Temperature [/action/check_temperature]

### Add and set check_temperature action [POST]

This route is for set and add the check_temperature action of weather servoce to a user.

+ city (string) - The city name
+ threshold (string) - The value for comparaison
+ symbol (string) - The symbol of comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "city": "Paris",
            "threshold": "5",
            "symbol": ">",
            "id": 6
        }

+ Response 200 (text/html)

        0

+ Response 503 (text/html)

        Error With the Database

## Action of Humidity [/action/check_humidity]

### Add and set check_humidity action [POST]

This route is for set and add the check_humidity action of weather service to a user.

+ city (string) - The city name
+ threshold (string) - The token to set
+ symbol (string) - The symbol of comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "city": "Toulouse",
            "threshold": "3",
            "symbol": "=",
            "id": 7
        }

+ Response 200 (text/html)

        1

+ Response 503 (text/html)

        Error With the Database

## Action of Crypto [/action/check_crypto_value]

### Add and set check_crypto_value action [POST]

This route is for set and add the check_crypto_value action of crypto service to a user.

+ crypto (string) - The crypto name
+ threshold (string) - The value for comparaison
+ symbol (string) - The symbol of comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "crypto": "Bitcoin",
            "threshold": "1600",
            "symbol": "<",
            "id": 19
        }

+ Response 200 (text/html)

        2

+ Response 503 (text/html)

        Error With the Database

## Action of Intra Project Time [/action/check_remaining_duration]

### Add and set check_remaining_duration action [POST]

This route is for set and add the check_remaining_duration action of intra service to a user.

+ project_name (string) - The project_name
+ time (string) - The value for time
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "project_name": "Stage temps partiel",
            "time": "80",
            "symbol": "=",
            "id": 33
        }

+ Response 200 (text/html)

        3

+ Response 503 (text/html)

        Error With the Database

## Action of Intra Recent Absence [/action/check_recent_absence]

### Add and set check_recent_absence action [POST]

This route is for set and add the check_recent_absence action of intra service to a user.

+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "id": 66
        }

+ Response 200 (text/html)

        4

+ Response 503 (text/html)

        Error With the Database

## Action of Intra Check Credit [/action/check_credit]

### Add and set check_credit action [POST]

This route is for set and add the check_credit action of intra service to a user.

+ number (string) - The number of credit to compare
+ symbol (string) - The symbol for comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "number": "120",
            "symbol": "=",
            "id": 33
        }

+ Response 200 (text/html)

        5

+ Response 503 (text/html)

        Error With the Database

## Action of Intra Check Gpa [/action/check_gpa]

### Add and set check_gpa action [POST]

This route is for set and add the check_gpa action of intra service to a user.

+ number (string) - The number of gpa to compare
+ symbol (string) - The symbol for comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "number": "4",
            "symbol": "<",
            "id": 88
        }

+ Response 200 (text/html)

        6

+ Response 503 (text/html)

        Error With the Database

## Action of Covid Check New Case [/action/check_new_case]

### Add and set check_new_case action [POST]

This route is for set and add the check_new_case action of covid service to a user.

+ country (string) - The country to observe
+ value (string) - The value to compare
+ symbol (string) - The symbol for comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "country": "France",
            "value": "1000"
            "symbol": "<",
            "id": 10
        }

+ Response 200 (text/html)

        7

+ Response 503 (text/html)

        Error With the Database

## Action of Covid Check New Death [/action/check_new_death]

### Add and set check_new_death action [POST]

This route is for set and add the check_new_death action of covid service to a user.

+ country (string) - The country to observe
+ value (string) - The value to compare
+ symbol (string) - The symbol for comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "country": "Kosovo",
            "value": "33"
            "symbol": "=",
            "id": 3
        }

+ Response 200 (text/html)

        8

+ Response 503 (text/html)

        Error With the Database

## Action of Covid Check New Recovered [/action/check_new_recovered]

### Add and set check_new_recovered action [POST]

This route is for set and add the check_new_recovered action of covid service to a user.

+ country (string) - The country to observe
+ value (string) - The value to compare
+ symbol (string) - The symbol for comparaison
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "country": "Kosovo",
            "value": "20"
            "symbol": "<",
            "id": 6
        }

+ Response 200 (text/html)

        9

+ Response 503 (text/html)

        Error With the Database

## Action of News [/action/check_last_news]

### Add and set check_last_news action [POST]

This route is for set and add the check_last_news action of news service to a user.

+ word (string) - The word to check
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "word": "Ukraine",
            "id": 52
        }

+ Response 200 (text/html)

        10

+ Response 503 (text/html)

        Error With the Database

## Action of Google Comments [/action/check_new_comment]

### Add and set check_new_comment action [POST]

This route is for set and add the check_new_comment action of google service to a user.

+ video (string) - The video id where check new comments (must be on your channel)
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "video": "67f9dd8879fc47b5a52514e80d6b03c9",
            "id": 52
        }

+ Response 200 (text/html)

        11

+ Response 503 (text/html)

        Error With the Database

## Action of Google Video [/action/check_new_video]

### Add and set check_new_video action [POST]

This route is for set and add the check_new_video action of google service to a user.

+ channel (string) - The channel id where check new video
+ id (number) - The ID of the user to add the action

+ Request (application/json)

        {
            "channel": "InvestigationEnquête",
            "id": 52
        }

+ Response 200 (text/html)

        12

+ Response 503 (text/html)

        Error With the Database

## Action Remove [/action/remove]

### Remove an action [POST]

This route is for remove an action who is linked to a user.

+ actionId (number) - The ID of action to remove
+ id (number) - The ID of the user to remove an action

+ Request (application/json)

        {
            "actionId": 1,
            "id": 2
        }

+ Response 200 (text/html)

        1

+ Response 503 (text/html)

        Error With the Database

# Group Reactions

## Email Reaction [/reaction/send_mail]

### Add and set send_mail reaction [POST]

This route is for set and add the send_mail reaction of the area service to a user.

+ email (string) - The email where to send the email reaction
+ message (string) - The message in the email who will send
+ actionId (number) - The id of action that will enable the reaction
+ id (number) - The ID of the user to add the reaction

+ Request (application/json)

        {
            "email": "test@test.com",
            "message": "Bonjour vous avez validé votre projet Area.",
            "actionId": 0,
            "id": 78
        }

+ Response 200 (text/html)

        13

+ Response 503 (text/html)

        Error With the Database

## Calendar Reaction [/reaction/new_calendar_event]

### Add and set new_calendar_event reaction [POST]

This route is for set and add the new_calendar_event reaction of the google service to a user.

+ title (string) - The title of the event that will be create
+ location (string) - The location of the event that will be create
+ description (string) - The description of the event that will be create
+ time (string) - The title of the duration (in day) of the event that will be create
+ actionId (number) - The id of action that will enable the reaction
+ id (number) - The ID of the user to add the reaction

+ Request (application/json)

        {
            "title": "Area Event",
            "location": "Epitech Paris",
            "description": "Bonjour vous avez validé votre projet Area.",
            "time": "2",
            "actionId": 0,
            "id": 78
        }

+ Response 200 (text/html)

        14

+ Response 503 (text/html)

        Error With the Database

## Reaction Remove [/reaction/remove]

### Remove an action [POST]

This route is for remove a reaction who is linked to a user and an action.

+ actionId (number) - The ID of action who is linked to the reaction to remove
+ reactionId (number) - The ID of reaction to remove
+ id (number) - The ID of the user to remove an action

+ Request (application/json)

        {
            "actionId": 1,
            "reactionId": 0,
            "id": 2
        }

+ Response 200 (text/html)

        0

+ Response 503 (text/html)

        Error With the Database

# Group About

## About json [/about.json]

### Get the about json [GET]

This route is for get the about json file that use for configure all the front.

+ Response 200 (text/html)

        {
            "services": [
                {
                    "name": "weather",
                    "actions": [
                        {
                            "name": "check_temperature",
                            "parameters": [
                                {
                                    "name": "city",
                                    "type": "string"
                                },
                                {
                                    "name": "threshold",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_humidity",
                            "parameters": [
                                {
                                    "name": "city",
                                    "type": "string"
                                },
                                {
                                    "name": "threshold",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        }
                    ],
                    "reactions": []
                },
                {
                    "name": "crypto",
                    "actions": [
                        {
                            "name": "check_crypto_value",
                            "parameters": [
                                {
                                    "name": "crypto",
                                    "type": "string"
                                },
                                {
                                    "name": "value",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        }
                    ],
                    "reactions": []
                },
                {
                    "name": "news",
                    "actions": [
                        {
                            "name": "check_last_news",
                            "parameters": [
                                {
                                    "name": "word",
                                    "type": "string"
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        }
                    ],
                    "reactions": []
                },
                {
                    "name": "google",
                    "actions": [
                        {
                            "name": "check_new_comment",
                            "parameters": [
                                {
                                    "name": "video",
                                    "type": "string"
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_new_video",
                            "parameters": [
                                {
                                    "name": "channel",
                                    "type": "string"
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        }
                    ],
                    "reactions": [
                        {
                            "name": "new_calendar_event",
                            "parameters": [
                                {
                                    "name": "title",
                                    "type": "string"
                                },
                                {
                                    "name": "location",
                                    "type": "string"
                                },
                                {
                                    "name": "description",
                                    "type": "string"
                                },
                                {
                                    "name": "time",
                                    "type": "string"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "intra",
                    "actions": [
                        {
                            "name": "check_remaining_duration",
                            "parameters": [
                                {
                                    "name": "project_name",
                                    "type": "string"
                                },
                                {
                                    "name": "time",
                                    "type": "string"
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_recent_absence",
                            "parameters": [],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_credit",
                            "parameters": [
                                {
                                    "name": "number",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_gpa",
                            "parameters": [
                                {
                                    "name": "number",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        }
                    ],
                    "reactions": []
                },
                {
                    "name": "covid",
                    "actions": [
                        {
                            "name": "check_new_case",
                            "parameters": [
                                {
                                    "name": "country",
                                    "type": "string"
                                },
                                {
                                    "name": "value",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_new_death",
                            "parameters": [
                                {
                                    "name": "country",
                                    "type": "string"
                                },
                                {
                                    "name": "value",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        },
                        {
                            "name": "check_new_recovered",
                            "parameters": [
                                {
                                    "name": "country",
                                    "type": "string"
                                },
                                {
                                    "name": "value",
                                    "type": "string"
                                },
                                {
                                    "name": "symbol",
                                    "type": "list",
                                    "values": [
                                        "<",
                                        ">",
                                        "="
                                    ]
                                }
                            ],
                            "reactions": [
                                "send_mail",
                                "new_calendar_event"
                            ]
                        }
                    ],
                    "reactions": []
                },
                {
                    "name": "area",
                    "actions": [],
                    "reactions": [
                        {
                            "name": "send_mail",
                            "parameters": [
                                {
                                    "name": "message",
                                    "type": "string"
                                },
                                {
                                    "name": "email",
                                    "type": "string"
                                }
                            ]
                        }
                    ]
                }
            ]
        }