version: "3"

services:
#   client:
#     build: client/
#     ports:
#       - "3000:3000"
#     expose:
#       - "3000"
#     stdin_open: true
#     depends_on:
#       - server
#     network_mode: host
  server:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    network_mode: host
  # db:
  #   image: mysql:5
  #   ports:
  #     - "3306:3306"
  #   expose:
  #     - "3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #   volumes:
  #     - db_volume:/var/lib/mysql
  #   network_mode: host

# volumes:
#   db_volume:
