version: '3'

services:
  server:
    build: ./server
    image: area-server:latest
    container_name: area-server
    restart: on-failure
    ports:
      - "3000:3000"
    network_mode: host

  db:
    image: mysql:5
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_volume:/var/lib/mysql
    network_mode: host

volumes:
  db_volume: