version: '3.8'

services:
  db:
    build: ./database
    image: area-database:latest
    container_name: area-database
    restart: always
    env_file:
      - ./database/.env
    volumes:
      - db_volume:/var/lib/mysql

  server:
    build: ./server
    image: area-server:latest
    container_name: area-server
    depends_on:
      - db
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  client:
    build: ./client
    image: area-client:latest
    container_name: area-client
    depends_on:
      - server
    restart: always
    ports:
      - "80:3000"

volumes:
  db_volume: