version: '3.8'

services:
  server:
    build: ./server
    image: area-server:latest
    container_name: area-server
    depends_on:
      - db
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - area

  db:
    image: mysql:5
    container_name: area-database
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - area

networks:
  area:

volumes:
  db_volume: